# permissions for end users to view adminadditionconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adminadditionconfig-viewer-role
rules:
- apiGroups:
  - addons.dana.io
  resources:
  - adminadditionconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.dana.io
  resources:
  - adminadditionconfigs/status
  verbs:
  - get
